#!/bin/bash

SCRIPT=`realpath $0`; DIRNAME=`dirname $SCRIPT`
source $DIRNAME/ProgressBar/progressbar.sh

DEBUGMODE=0

# Helper functions for precise units
kb2gb() {
  echo "$1" "$2" | awk '{ foo = ($1 + $2) / 1024 / 1024 ; print foo }'
}

percentage() {
  echo "$1" "$2" | awk '{ print ($1 / ($1 + $2)) * 100 }' 
}

# Do some free space calculations with df and awk
dfk=`df -k /home`
kbused=`echo "$dfk" | awk 'NR == 2 { print $3 }'`
kbfree=`echo "$dfk" | awk 'NR == 2 { print $4 }'`
gbtotal=`kb2gb $kbused $kbfree`
gbused=`kb2gb $kbused`
gbfree=`kb2gb $kbfree`
gbtotali=`printf "%'.f\n" $gbtotal`
gbusedi=`printf "%'.f\n" $gbused`
gbusedf=`printf "%'.3f\n" $gbused`
gbfreef=`printf "%'.3f\n" $gbfree`
percentused=`percentage $kbused $kbfree`
percentfree=`percentage $kbfree $kbused`

# Make it into something readable
read -r -d '' message << EOM
**$gbusedf GB Used**, $gbfreef GB Remaining
`ProgressBar $gbusedi $gbtotali "Usage"`
\`[`TZ=America/New_York date +"%r"` EST]\`
EOM

if [ $DEBUGMODE -eq 1 ]; then
  echo "Not sending message:"
  echo "$message"
else
  $DIRNAME/send-message "Disk Usage Report" "$message"
fi

